config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :books
  get 'about', to: 'pages#about'
  get 'books', to: 'books#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    # Validation in place for required fields
    validates :title, :presence => true
    validates :author, :presence => true
    validates :ISBN, :presence => true
    validates :date, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
    # Validation on place for required fields
    validates :title, :presence => true
    validates :name, :presence => true
    validates :dob, :presence => true
    validates :role, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create

    # Catchment logic in place to always set loaned to null if loan status is false/0
    copy_params = book_params
    if copy_params[:loan_status] == "0"
      copy_params[:loaned_to] = nil
    end

    @book = Book.new(copy_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update

    # Catchment logic in place to always set loaned to null if loan status is false/0
    copy_params = book_params
    if copy_params[:loan_status] == "0"
      copy_params[:loaned_to] = nil
    end
    respond_to do |format|
      if @book.update(copy_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :ISBN, :date, :loan_status, :loaned_to)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy

    # Catchment logic in place to reset loaned to value for Books relating to user being destroyed
    Book.where(loaned_to: @user.name).update(loan_status: false, loaned_to: nil)

    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:title, :name, :dob, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # Method to convert loan status into descriptive string
    def convert_loan_status(loan_status)
        if loan_status === true
          "On loan"
        else
          "Available"
        end
      end
    
    # Method to trim UTC
    def remove_trailing_UTC(created_at)
        created_at.strftime("%a, %d %b %Y %H:%M:%S")
    end

    # Method to return more descriptive loan text based on username prescence
    def encrich_onLoan_text(user_name)
        if user_name != nil 
            "This book is on loan to user " + user_name
        else 
            "This book is not on loan"
        end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div style="display:flex; flex-direction: column; width: 100%; height: 80%; align-items: center; justify-content: space-around;">
  <h1 style="color: white;">View</h1>
  <div id="<%= dom_id book %>" style="display: flex; flex-direction: row; background: black; border-radius: 10px; color: white; padding: 20px; width: 80%; height: 80%; align-items: stretch; font-size: 1.8rem;">
    <div style="display:flex; flex-direction: column; justify-content: space-between; flex: 1 1 0; ">
      <div><p style="font-size: 4rem">
          <strong><%= book.title %></strong>
        </p>

        <p>
          by <%= book.author %>
        </p>
      </div>

        <p>
          Released <%= book.date %>
        </p>
    </div>
    <div style="display:flex; flex-direction: column; flex: 1 1 0; background: linear-gradient(white, grey); border-radius: 10px; padding: 20px; color: black; font-size: 1.6rem; justify-content: space-around;">
      <p>
        <strong>System Details</strong>
      </p>
      <p>
        <strong>Isbn:</strong>
        <%= book.ISBN %>
      </p>

      <p>
        <strong>Uploaded:</strong>
        <%= remove_trailing_UTC(book.created_at) %>
      </p>

      <p><strong>Loan status:</strong>
        <%= convert_loan_status(book.loan_status) %>
      </p>

      <p>
        <strong>Loaned to:</strong>
        <%= encrich_onLoan_text(book.loaned_to) %>
      </p>
        <div style="display: flex; justify-content: space-around; width: 100%;">
        
        <%= link_to '<button type="button" class="btn btn-dark btn-lg">Back to Books</button>'.html_safe, books_path %>
        <%= link_to '<button type="button" class="btn btn-dark btn-lg">Edit</button>'.html_safe, edit_book_path(@book) %>

        <%= button_to "Delete", @book, method: :delete, data: {  }, :class => "btn btn-dark btn-lg" %>
        </div>

    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <div style="margin-top: 10px;">
    <%= form.label :title, style: "display: block; color: white; font-size: 1.2rem;" %>
    <%= form.text_field :title, style: "border-radius: 5px; border: none; font-size: 1.2rem;" %>
  </div>

  <div style="margin-top: 5px;">
    <%= form.label :author, style: "display: block; color: white; font-size: 1.2rem;" %>
    <%= form.text_field :author, style: "border-radius: 5px; border: none; font-size: 1.2rem;" %>
  </div>

  <div style="margin-top: 5px;">
    <%= form.label :ISBN, style: "display: block; color: white; font-size: 1.2rem;" %>
    <%= form.number_field :ISBN, style: "border-radius: 5px; border: none; font-size: 1.2rem;" %>
  </div>

  <div style="margin-top: 5px;">
    <%= form.label :date, style: "display: block; color: white; font-size: 1.2rem;" %>
    <%= form.date_field :date, style: "border-radius: 5px; border: none; font-size: 1.2rem;" %>
  </div>

  <div style="margin-top: 5px;">
    <%= form.label :loan_status, style: "display: block; color: white; font-size: 1.2rem;" %>
    <%= form.check_box :loan_status %>
  </div>

  <div style="margin-top: 5px;">
    <%= form.label :loaned_to, style: "display: block; color: white; font-size: 1.2rem;" %>
    <%= collection_select(:book, :loaned_to, User.all, :name, :name,{:include_blank => "Please Select"} , { :disabled => !@book.loan_status ? 'disabled' : nil}) %>
  </div>

  <div style="margin-top: 15px; width: 100%; display: flex; align-items: center; justify-content: center;">
    <%= form.submit class: "btn btn-dark" %>
  </div>

  <% if book.errors.any? %>
    <div style="color: red; font-size: 1rem; left: 0; position: absolute; bottom: 30px; width: 100%; text-align: center;">
      <p><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:

      
        <% book.errors.each_with_index do |error, index| %>
          <%= error.full_message %>
           <%= "," unless index == book.errors.size - 1 %>
        <% end %>
      </p>
    </div>
  <% end %>
<% end %>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js">
    </script>

<script type="text/javascript" >
    $(document).ready(function () {
    return $("#book_loan_status").click(function () {
          $("#book_loaned_to option:first").prop('selected',true);
        if (this.checked) { 
          $("#book_loaned_to").prop('required',true);
        }
        return $("#book_loaned_to").prop("disabled", !this.checked);
    });
});
</script>

app/views/books/edit.html.erb
<div style="display:flex; flex-direction: column; width: 100%; height: 80%; align-items: center; justify-content: center;">

<h1 style="color: white; margin-top: 50px;">Edit</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to '<button type="button" class="btn btn-light">View</button>'.html_safe, @book %>
  <%= link_to '<button type="button" class="btn btn-light">Back to Books</button>'.html_safe, books_path %>
</div>
</div>

app/views/books/index.html.erb
<div class="container-fluid text-center text-white" style="margin-top: 20px;">

<h1>Books</h1>

<div class="twrap" style="margin-top: 50px;">
<table class="table table-light table-hover" style=" text-align: left;">
  <thead class="fixed">
    <tr>
      <th scope="col" width="5%">ID</th>
      <th scope="col" width="15%">Title</th>
      <th scope="col" width="20%">Author</th>
      <th scope="col" width="10%">ISBN</th>
      <th scope="col" width="10%">Release Date</th>
      <th scope="col" width="10%">Loan Status</th>
      <th scope="col" width="15%">Upload Date</th>
      <th scope="col" width="5%"></th>
      <th scope="col" width="5%"></th>
      <th scope="col" width="5%"></th>
    </tr>
  </thead>
  <tbody style="overflow-y: scroll;">
    <% @books.each do |book| %>
    <tr id="<%= dom_id book %>">
      <th scope="row"><%= book.id %></th>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.ISBN %></td>
      <td><%= book.date %></td>
      <td><%= convert_loan_status(book.loan_status) %></td>
      <td><%= book.created_at %></td>
      <td><%= link_to '<button type="button" class="btn btn-light btn-sm">View</button>'.html_safe, book %></td>
      <td><%= link_to '<button type="button" class="btn btn-light btn-sm">Edit</button>'.html_safe, edit_book_path(book) %></td>
      <td><%= button_to "Delete", book, method: :delete, data: {  }, :class => "btn btn-light btn-sm" %></td>
</tr>
  <% end %>
  </tbody>
</table>
</div>
<%= link_to '<button style="margin-top: 25px;" type="button" class="btn btn-dark btn-lg">Add Book</button>'.html_safe, new_book_path %>
</div>

app/views/books/new.html.erb
<div style="display:flex; flex-direction: column; width: 100%; height: 80%; align-items: center; justify-content: center;">

<h1 style="color: white; margin-top: 50px;">Add</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to '<button type="button" class="btn btn-light">Back to Books</button>'.html_safe, books_path %>
</div>
</div>

app/views/books/show.html.erb
<%= render @book %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Books", books_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class:"nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid text-center text-white" style="margin-top: 150px;">
 <h1>Welcome to the Library Administration Application!</h1>
    <p style="margin-top: 50px; margin-bottom: 50px;">Use the buttons below or the Navbar to view books and users stored in this system. From these pages you will also be able to add, remove and edit items.</p>
    
        <%= link_to '<button type="button" style="margin-right: 50px;" class="btn btn-light btn-lg">Books</button>'.html_safe, books_path %>
        <%= link_to '<button type="button" style="margin-left: 50px;" class="btn btn-light btn-lg">Users</button>'.html_safe, users_path %>
    
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <div style="margin-top: 10px;">
    <%= form.label :title, style: "display: block; color: white; font-size: 1.2rem;" %>
    <%= form.text_field :title, style: "border-radius: 5px; border: none; font-size: 1.2rem;" %>
  </div>

  <div style="margin-top: 5px;">
    <%= form.label :name, style: "display: block; color: white; font-size: 1.2rem;" %>
    <%= form.text_field :name, style: "border-radius: 5px; border: none; font-size: 1.2rem;" %>
  </div>

  <div style="margin-top: 5px;">
    <%= form.label :dob, style: "display: block; color: white; font-size: 1.2rem;" %>
    <%= form.date_field :dob, style: "width: 100%; border-radius: 5px; border: none; font-size: 1.2rem;" %>
  </div>

  <div style="margin-top: 5px;">
    <%= form.label :role, style: "display: block; color: white; font-size: 1.2rem;" %>
    <%= form.text_field :role, style: "border-radius: 5px; border: none; font-size: 1.2rem;" %>
  </div>

  <div style="margin-top: 15px; width: 100%; display: flex; align-items: center; justify-content: center;">
    <%= form.submit class: "btn btn-dark" %>
  </div>

  <% if user.errors.any? %>
    <div style="color: red; font-size: 1rem; left: 0; position: absolute; bottom: 30px; width: 100%; text-align: center;">
      <p><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:

      
        <% user.errors.each_with_index do |error, index| %>
          <%= error.full_message %>
           <%= "," unless index == user.errors.size - 1 %>
        <% end %>
      </p>
    </div>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<div style="display:flex; flex-direction: column; width: 100%; height: 80%; align-items: center; justify-content: center;">

<h1 style="color: white;">View</h1>

<div id="<%= dom_id user %>" style="display: flex; flex-direction: column; background: black; border-radius: 10px; color: white; padding: 20px; width: 30%; height: 80%; align-items: center; font-size: 1.8rem;">
  <div style="display: flex; flex-direction: column; margin-top: 30px;">
  <p>
    <strong>Title:</strong>
    <%= user.title %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= user.dob %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>
  </div>
  <div style="display: flex; justify-content: space-around; width: 80%; align-self: center; margin-top: 50px;">
        
        <%= link_to '<button type="button" class="btn btn-light btn-lg">Back to Users</button>'.html_safe, users_path %>
        <%= link_to '<button type="button" class="btn btn-light btn-lg">Edit</button>'.html_safe, edit_user_path(@user) %>

        <%= button_to "Delete", @user, method: :delete, data: {  }, :class => "btn btn-light btn-lg" %>
        </div>

</div>
</div>

app/views/users/edit.html.erb
<div style="display:flex; flex-direction: column; width: 100%; height: 80%; align-items: center; justify-content: center;">

<h1 style="color: white;">Edit</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to '<button type="button" class="btn btn-light">View</button>'.html_safe, @user %>
  <%= link_to '<button type="button" class="btn btn-light">Back to Users</button>'.html_safe, users_path %>
</div>
</div>

app/views/users/index.html.erb
<div class="container-fluid text-center text-white" style="margin-top: 20px;">

<h1>Users</h1>

<div class="twrap" style="margin-top: 50px;">
<table class="table table-light table-hover" style=" text-align: left;">
  <thead class="fixed">
    <tr>
      <th scope="col" width="5%">ID</th>
      <th scope="col" width="10%">Title</th>
      <th scope="col" width="20%">Name</th>
      <th scope="col" width="15%">DOB</th>
      <th scope="col" width="10%">Role</th>
      <th scope="col" width="25%">Date Added</th>
      <th scope="col" width="5%"></th>
      <th scope="col" width="5%"></th>
      <th scope="col" width="5%"></th>
    </tr>
  </thead>
  <tbody style="overflow-y: scroll;">
    <% @users.each do |user| %>
    <tr id="<%= dom_id user %>">
      <th scope="row"><%= user.id %></th>
      <td><%= user.title %></td>
      <td><%= user.name %></td>
      <td><%= user.dob %></td>
      <td><%= user.role %></td>
      <td><%= user.created_at %></td>
      <td><%= link_to '<button type="button" class="btn btn-light btn-sm">View</button>'.html_safe, user %></td>
      <td><%= link_to '<button type="button" class="btn btn-light btn-sm">Edit</button>'.html_safe, edit_user_path(user) %></td>
      <td><%= button_to "Delete", user, method: :delete, data: {  }, :class => "btn btn-light btn-sm" %></td>
</tr>
  <% end %>
  </tbody>
</table>
</div>
<%= link_to '<button style="margin-top: 25px;" type="button" class="btn btn-dark btn-lg">Add User</button>'.html_safe, new_user_path %>
</div>

app/views/users/new.html.erb
<div style="display:flex; flex-direction: column; width: 100%; height: 80%; align-items: center; justify-content: center;">

<h1 style="color: white;">Add</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to '<button type="button" class="btn btn-light">Back to Users</button>'.html_safe, users_path %>
</div>
</div>

app/views/users/show.html.erb
<%= render @user %>